/* User Authentication - Types */
export const ADD_NHS_USER_TOKEN = 'ADD_NHS_USER_TOKEN'
export const ADD_NHS_USER_INFO = 'ADD_NHS_USER_INFO'
export const ADD_USER_CONFIGURATION = 'ADD_USER_CONFIGURATION'

/* SSO User Authentication (TMP Redux) - Types */
export const ACCESS_TOKEN_EXPIRED = 'ACCESS_TOKEN_EXPIRED'
export const REMOVE_NHS_APP_DETAILS = 'REMOVE_NHS_APP_DETAILS'
export const REFRESH_SSO_TMP_NHS_USER_TOKEN = 'REFRESH_SSO_TMP_NHS_USER_TOKEN'
export const ADD_TMP_USER_TOKEN = 'ADD_TMP_USER_TOKEN'
export const ADD_TMP_USER_CONFIGURATION = 'ADD_TMP_USER_CONFIGURATION'
export const REMOVE_TMP_TOKEN_INFO = 'REMOVE_TMP_TOKEN_INFO'

/* API Cache - Types */
export const CACHE_DOMESTIC_CERTIFICATE_VALUES = 'CACHE_DOMESTIC_CERTIFICATE_VALUES'
export const CACHE_INTERNATIONAL_CERTIFICATE_VALUES = 'CACHE_INTERNATIONAL_CERTIFICATE_VALUES'
export const CACHE_INTERNATIONAL_RECOVERY_VALUES = 'CACHE_INTERNATIONAL_RECOVERY_VALUES'
export const CACHE_VACCINATION_RESULTS = 'CACHE_VACCINATION_RESULTS'
export const CACHE_TEST_RESULTS = 'CACHE_TEST_RESULTS'
export const CACHE_EXEMPTION_RESULTS = 'CACHE_EXEMPTION_RESULTS'
export const CACHE_RECOVERY_TEST_RESULTS = 'CACHE_RECOVERY_TEST_RESULTS'
export const CACHE_DOMESTIC_CERTIFICATE_PDF_BLOB_EN = 'CACHE_DOMESTIC_CERTIFICATE_PDF_BLOB_EN'
export const CACHE_DOMESTIC_CERTIFICATE_PDF_BLOB_CY = 'CACHE_DOMESTIC_CERTIFICATE_PDF_BLOB_CY'
export const CACHE_INTERNATIONAL_CERTIFICATE_PDF_BLOB_EN =
    'CACHE_INTERNATIONAL_CERTIFICATE_PDF_BLOB_EN'
export const CACHE_INTERNATIONAL_CERTIFICATE_PDF_BLOB_CY =
    'CACHE_INTERNATIONAL_CERTIFICATE_PDF_BLOB_CY'
export const CACHE_GOOGLE_WALLET_DOMESTIC_URL = 'CACHE_GOOGLE_WALLET_DOMESTIC_URL'
export const CACHE_PDF_DOMESTIC_DOWNLOAD_LIMIT_EXPIRY = 'CACHE_PDF_DOMESTIC_DOWNLOAD_LIMIT_EXPIRY'
export const CACHE_PDF_INTERNATIONAL_DOWNLOAD_LIMIT_EXPIRY =
    'CACHE_PDF_INTERNATIONAL_DOWNLOAD_LIMIT_EXPIRY'

/* Unauthenticated User - Types*/
export const REMOVE_USER = 'REMOVE_USER'
export const REMOVE_USER_CACHE = 'REMOVE_USER_CACHE'
export const REMOVE_ALL_REDUX = 'REMOVE_ALL_REDUX'

/* Other - Types*/
export const UPDATE_NHS_APP_DESKTOP = 'UPDATE_NHS_APP_DESKTOP'
export const TOGGLE_FOOTER = 'TOGGLE_FOOTER'
export const UPDATE_SELECTED_FLOW = 'UPDATE_SELECTED_FLOW'
export const EMAIL_LIMIT = 'EMAIL_LIMIT'
export const LANGUAGE_TOGGLE = 'LANGUAGE_TOGGLE'
export const TOGGLE_SURVEY_BANNER = 'TOGGLE_SURVEY_BANNER'

/* Feature Toggle - Types */
export const UPDATE_APPLE_WALLET_TOGGLE = 'UPDATE_APPLE_WALLET_TOGGLE'
export const UPDATE_GOOGLE_WALLET_TOGGLE = 'UPDATE_GOOGLE_WALLET_TOGGLE'
export const UPDATE_SHOW_PDF_DOWNLOAD = 'UPDATE_SHOW_PDF_DOWNLOAD'
export const UPDATE_DOMESTIC_TOGGLE = 'UPDATE_DOMESTIC_TOGGLE'
